export const testimonials = [
  {
    name: 'Sarah Larson',
    role: 'Anxiety Recovery',
    avatar: '/images/1438761681033.webp',
    text: 'Life-changing. After years of battling anxiety, I finally sought help — and I am so grateful I did. My counselor was incredibly kind and supportive.',
    stars: 5,
    service: 'Individual Therapy',
  },
  {
    name: 'Marcus Lane',
    role: 'Online Therapy Client',
    avatar: '/images/1500648767791.webp',
    text: 'The online sessions made it so easy to get help without stepping out of my comfort zone. I felt just as connected and cared for.',
    stars: 5,
    service: 'Online Counseling',
  },
  {
    name: 'Hannah Mitchell',
    role: 'Grief Counseling',
    avatar: '/images/1544005313.webp',
    text: 'After losing my father, I struggled deeply. My grief therapist helped me find space for the pain, without letting it define me.',
    stars: 5,
    service: 'Grief Support',
  },
  {
    name: 'Daniel F.',
    role: 'Relationship Support',
    avatar: '/images/1507003211169.webp',
    text: 'I was going through a difficult breakup. Counseling gave me the tools to heal. I felt safe, respected, and heard from day one.',
    stars: 5,
    service: 'Relationship Support',
  },
  {
    name: 'Amelia Chen',
    role: 'Stress Management',
    avatar: '/images/1534528741775.webp',
    text: 'I did not realize how much stress was affecting my health until I started therapy. Now I have real tools to manage it.',
    stars: 5,
    service: 'Stress Management',
  },
  {
    name: 'Olivia Grant',
    role: 'Trauma Recovery',
    avatar: '/images/1524504388940.webp',
    text: 'My therapist helped me feel safe in my own story again. Every session felt steady, respectful, and empowering.',
    stars: 5,
    service: 'Trauma Therapy',
  },
];
