export const categories = ['All', 'Mental Health', 'Therapy', 'Mindfulness', 'Relationships', 'Self Care'];

export const posts = [
  {
    slug: 'how-to-start-therapy-with-confidence',
    title: 'How to Start Therapy with Confidence',
    excerpt: 'A gentle guide to preparing for your first therapy session and knowing what to expect along the way.',
    category: 'Therapy',
    date: 'Jan 12, 2026',
    readTime: '6 min read',
    author: 'Dr. Sarah Mitchell',
    image: '/images/1573497620053.webp',
    featured: true,
  },
  {
    slug: 'simple-grounding-techniques-for-anxiety',
    title: 'Simple Grounding Techniques for Anxiety',
    excerpt: 'Practical grounding exercises you can use anytime anxiety feels overwhelming or hard to control.',
    category: 'Mental Health',
    date: 'Jan 08, 2026',
    readTime: '5 min read',
    author: 'Priya Sharma',
    image: '/images/1506126613408.webp',
    featured: false,
  },
  {
    slug: 'building-healthier-communication-in-relationships',
    title: 'Building Healthier Communication in Relationships',
    excerpt: 'Learn how active listening, emotional honesty, and repair conversations can strengthen connection.',
    category: 'Relationships',
    date: 'Dec 28, 2025',
    readTime: '7 min read',
    author: 'James Carter',
    image: '/images/1516589178581.webp',
    featured: false,
  },
  {
    slug: 'mindfulness-for-busy-days',
    title: 'Mindfulness for Busy Days',
    excerpt: 'Small practices that help you slow down, breathe deeper, and feel present even on demanding days.',
    category: 'Mindfulness',
    date: 'Dec 20, 2025',
    readTime: '4 min read',
    author: 'Daniel Okafor',
    image: '/images/1545205597.webp',
    featured: false,
  },
  {
    slug: 'why-self-care-is-not-selfish',
    title: 'Why Self Care Is Not Selfish',
    excerpt: 'Reframing self care as a foundation for resilience, healthy boundaries, and emotional energy.',
    category: 'Self Care',
    date: 'Dec 14, 2025',
    readTime: '5 min read',
    author: 'Dr. Sarah Mitchell',
    image: '/images/1527689368864.webp',
    featured: false,
  },
  {
    slug: 'understanding-trauma-informed-care',
    title: 'Understanding Trauma-Informed Care',
    excerpt: 'What trauma-informed therapy means and how it helps create safety, trust, and empowerment.',
    category: 'Therapy',
    date: 'Dec 05, 2025',
    readTime: '8 min read',
    author: 'Priya Sharma',
    image: '/images/1559757175.webp',
    featured: false,
  },
];
